* remade build script

diff --git a/scripts/fakeroot.in b/scripts/fakeroot.in
--- a/scripts/fakeroot.in
+++ b/scripts/fakeroot.in
@@ -1,23 +1,26 @@
 #!/bin/sh
 
-# This script first starts faked (the daemon), and then it will run
+# This script first starts fakechrootd (the daemon), and then it will run
 # the requested program with fake root privileges.
 
 usage () {
-  echo >&2 "fakechroot, create a fake chroot environment."
-  echo >&2 "   usage: fakeroot [-l|--lib fakerootlib] [-r|--faked fakedbin]"
-  echo >&2 "                   [-i file] [-s file] [-u|--unknown-is-real]"
-  echo >&2 "                   [--] [command]"
+cat - >&2 <<EOF
+fakeroot, create a fake root environment.
+   usage: fakechroot [-l|--lib fakechrootlib] [-r|--faked fakedbin]
+                   [-i file] [-s file] [-u|--unknown-is-real]
+		   [-b|--fd-base fd] [-h|--help] [-v|--version]
+                   [--] [command]
+EOF
   exit 1
 }
 
-# strip /bin/fakechroot to find install prefix
-BINDIR=`dirname $0`
-PREFIX=`dirname ${BINDIR}`
+# strip /bin/fakeroot to find install prefix
+PREFIX=@prefix@
+BINDIR=@bindir@
     
-LIB=libfakechroot.so.0
-PATHS=${PREFIX}/lib/libfakechroot:${PREFIX}/lib64/libfakechroot
-FAKED=${BINDIR}/faked
+LIB=lib@fakeroot_transformed@.so.0
+PATHS=@libdir@:${PREFIX}/lib64/libfakechroot
+FAKED=${BINDIR}/@faked_transformed@
 
 FAKED_MODE="unknown-is-root"
 export FAKED_MODE
@@ -27,14 +30,14 @@ libfound=no
 GETOPTEST=`getopt --version`
 case $GETOPTEST in
 getopt*) # GNU getopt
-    TEMP=`getopt -l lib: -l faked: -l unknown-is-real -- +l:f:i:s:u "$@"`
+    TEMP=`getopt -l lib: -l faked: -l unknown-is-real -l fd-base: -l version -l help -- +l:f:i:s:ub:vh "$@"`
     ;;
 *) # POSIX getopt ?
-    TEMP=`getopt l:f:i:s:u "$@"`
+    TEMP=`getopt l:f:i:s:ub:vh "$@"`
     ;;
 esac
 
-if test "$?" != "0"; then
+if test "$?" -ne 0; then
   usage
 fi
 
@@ -42,6 +45,8 @@ eval set -- "$TEMP"
 
 FAKEDOPTS=""
 PIPEIN=""
+WAITINTRAP=0
+
 while test "X$1" != "X--"; do
   case "$1" in
     -l|--lib)
@@ -55,16 +60,29 @@ while test "X$1" != "X--"; do
        ;;
     -i)
        shift
-       FAKEDOPTS=$FAKEDOPTS" --load"
-       PIPEIN="<$1"
+       if test -f "$1"; then
+         FAKEDOPTS=$FAKEDOPTS" --load"
+         PIPEIN="<$1"
+       else
+         echo 1>&2 "fakechroot: database file \`$1' does not exist."
+       fi
        ;;
     -s)
        shift
        FAKEDOPTS=$FAKEDOPTS" --save-file $1"
+       WAITINTRAP=1
        ;;
     -u|--unknown-is-real)
        FAKEDOPTS=$FAKEDOPTS" --unknown-is-real"
        FAKED_MODE="unknown-is-real"
+       ;;
+    -b|--fd-base)
+       shift
+       FAKEROOT_FD_BASE="$1"
+       ;;
+    -v|--version)
+       echo "fakechroot version @VERSION@"
+       exit 0
        ;;
     -h|--help)
        usage
@@ -94,7 +112,7 @@ fi
 
 if test $libfound = no
 then
-    echo >&2 "fakechroot: preload library not found, aborting."
+    echo >&2 "fakeroot: preload library not found, aborting."
     exit 1
 fi
 
@@ -103,7 +121,11 @@ KEY_PID=`eval $FAKED $FAKEDOPTS $PIPEIN`
 FAKEROOTKEY=`echo $KEY_PID|cut -d: -f1`
 PID=`echo $KEY_PID|cut -d: -f2`
 
-trap "kill -s TERM $PID" EXIT INT
+if [ "$WAITINTRAP" -eq 0 ]; then
+  trap "kill -s TERM $PID" EXIT INT
+else
+  trap "kill -s TERM $PID ; wait $PID >/dev/null 2>&1" EXIT INT
+fi
 
 if test -z "$FAKEROOTKEY" || test -z "$PID"; then
   echo >&2 "fakechroot: error while starting the \`faked' daemon."
@@ -118,6 +140,8 @@ fi
 if test -n "$LD_PRELOAD"; then
   LIB="$LIB $LD_PRELOAD"
 fi
+
+export FAKEROOT_FD_BASE
 
 if test -z "$*"; then
   FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB" ${SHELL:-/bin/sh}
